version: "3"
services:
  nginx-php-fpm:
    image: mmm
    ports:
      - 891:80
#    stdin_open: true
    tty: true
    volumes:
      - ./nginx/include:/usr/local/nginx/conf/include
      - ./nginx/html/php_nginx:/usr/local/nginx/html/php_nginx
      - ./nginx/html/vue_nginx:/usr/local/nginx/html/vue_nginx
      - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./nginx/logs:/data/nginx/logs:rw